--- 
user: admin
group: admin
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
#socket: tmp/sockets/thin.sock
chdir: .
tag: a-name-to-show-up-in-ps aux
address: 0.0.0.0
port: 1792
